sudo: required

services:
  - docker

before_install:
  - docker build -t rumi/docker-nextjs -f Dockerfile.dev .

script:
  - docker run rumi/docker-nextjs npm run test -- --passWithNoTests

cache:
  directories:
    - node_modules